# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=228, upload_to=''),
            preserve_default=False,
        ),
    ]
