# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0005_auto_20160703_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/static/app/images'),
        ),
    ]
