# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0019_auto_20160704_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
    ]
